### ISSUE TITLE
compiler making noise 

### ISSUE THREAD

**Issue by amsterdam246** [fnarify/VS1053-Arduino-Music-Player#2]
hi f, m having an issue with  the compiler making noise >>invalid conversion from 'const byte* {aka const unsigned char*}' to 'byte* {aka unsigned char*}'
I donno wat the  issue could be. i have attached a screenshot of the actual compiler complaints

**Comment by fnarify** [comment]
All of the warnings that do pop-up won't affect the operation of the code, but those warnings can be removed by making these changes listed below:

**line 99 & 100:** remove const keyword from those variables (seems to be due to a lack of keywords in the provided version of the Keypad library, which leads to warnings)

**line 660 & 724:**
`printTrackInfo((char *) extra_command);`
**line 665:**
`Serial.println(record((char *) extra_command));`
**line 718:**
`result = MP3player.playMP3((char *) extra_command, offset_ms);`
These make the cast explicit from a byte array to a character array. You can technically change the variables buff and cur in the loop() function to characters and then change the various function definitions from having byte to char. In the end it doesn't matter what you choose, as these type casts do not need to be explicit.

**line 898:**
```
  char pluginname[] = "oggenc.053";
  if (MP3player.VSLoadUserCode(pluginname)) {
```
You can bring the string out of the VSLoadUserCode function to remove this warning by making a separate variable for it above.

There are two other warnings that suggest adding parenthesis around lines 282 and 542, you can add these if you want. Lastly, there's a complaint about playMIDIbeep not being handled in the switch statement on line 1082, it doesn't matter if it falls through, so you can ignore that. However, if you want the error to go away you can add after the last case in that switch statement block:
```
default:
    break;
```

I assume these are the compiler problems you are talking about, if they aren't I'd need that screenshot or a bit more detail about where they are. I've just gone through the code with more compiler warnings turned on and fixed what appeared.

**Comment by amsterdam246** [comment]
Hey fnarify, thanks for the response I dd all u told me and the code dd
work just fine and if m to politely ask if u can do a version where u
browse through the playlist and select a song of ur choice,and thanks very
much for the awesome work

**Comment by fnarify** [comment]
After including the required external libraries, there was very little SRAM left on an Arduino UNO to implement everything the project does and leave enough memory for variable allocation. You'd need an Arduino Mega or similar to be able to come up with an implementation that lets you browse the playlist on a screen. I initially tried to do something similar but deemed it unfeasible without reimplementing the external libraries.

A compromise is that you can perform this without change via the serial input, inputting 'd' into the serial terminal will display all files in the current directory of the SD card (see line 728). You can then directly play files via the command 'f filename' in the serial terminal. The experimental version of the software (under its own sub-folder) allows you to enter the filename directly of a track using the keypad, but won't display every file on the SD card.

For reference, each file on the SD card should have a unique int reference value. This value can be used to easily access files on the SD card without needing the full filename, you can see this in the function createPlaylist() on line 586. If you could easily take this reference value and return the associated filename, you could build the playlist by working in reverse.
